# -*- coding: utf-8 -*-
"""A2_RNNs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/PelagiaKalpakidou/Deep_Learning_2/blob/main/A2_RNNs.ipynb

<div style="text-align: right">   </div>


Introduction to Deep Learning (2023) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| &nbsp;
-------|-------------------
**Assignment 2 - Recurrent Neural Networks** | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/UniversiteitLeidenLogo.svg/1280px-UniversiteitLeidenLogo.svg.png" width="300">



# Introduction


The goal of this assignment is to learn how to use encoder-decoder recurrent neural networks (RNNs). Specifically we will be dealing with a sequence to sequence problem and try to build recurrent models that can learn the principles behind simple arithmetic operations (**integer addition, subtraction and multiplication.**).

<img src="https://i.ibb.co/5Ky5pbk/Screenshot-2023-11-10-at-07-51-21.png" alt="Screenshot-2023-11-10-at-07-51-21" border="0" width="500"></a>

In this assignment you will be working with three different kinds of models, based on input/output data modalities:
1. **Text-to-text**: given a text query containing two integers and an operand between them (+ or -) the model's output should be a sequence of integers that match the actual arithmetic result of this operation
2. **Image-to-text**: same as above, except the query is specified as a sequence of images containing individual digits and an operand.
3. **Text-to-image**: the query is specified in text format as in the text-to-text model, however the model's output should be a sequence of images corresponding to the correct result.


### Description**
Let us suppose that we want to develop a neural network that learns how to add or subtract
two integers that are at most two digits long. For example, given input strings of 5 characters: ‘81+24’ or
’41-89’ that consist of 2 two-digit long integers and an operand between them, the network should return a
sequence of 3 characters: ‘105 ’ or ’-48 ’ that represent the result of their respective queries. Additionally,
we want to build a model that generalizes well - if the network can extract the underlying principles behind
the ’+’ and ’-’ operands and associated operations, it should not need too many training examples to generate
valid answers to unseen queries. To represent such queries we need 13 unique characters: 10 for digits (0-9),
2 for the ’+’ and ’-’ operands and one for whitespaces ’ ’ used as padding.
The example above describes a text-to-text sequence mapping scenario. However, we can also use different
modalities of data to represent our queries or answers. For that purpose, the MNIST handwritten digit
dataset is going to be used again, however in a slightly different format. The functions below will be used to create our datasets.

---

*To work on this notebook you should create a copy of it.*

# Function definitions for creating the datasets

First we need to create our datasets that are going to be used for training our models.

In order to create image queries of simple arithmetic operations such as '15+13' or '42-10' we need to create images of '+' and '-' signs using ***open-cv*** library. We will use these operand signs together with the MNIST dataset to represent the digits.
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import cv2
import numpy as np
import tensorflow as tf
import random
from sklearn.model_selection import train_test_split

from tensorflow.keras.layers import Dense, LSTM, TimeDistributed
from tensorflow.keras.layers import RepeatVector, Reshape, Conv2DTranspose, LayerNormalization, BatchNormalization, Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split

from scipy.ndimage import rotate
# Create plus/minus operand signs
def generate_images(number_of_images=50, sign='-'):

    blank_images = np.zeros([number_of_images, 28, 28])  # Dimensionality matches the size of MNIST images (28x28)
    x = np.random.randint(12, 16, (number_of_images, 2)) # Randomized x coordinates
    y1 = np.random.randint(6, 10, number_of_images)       # Randomized y coordinates
    y2 = np.random.randint(18, 22, number_of_images)     # -||-

    for i in range(number_of_images): # Generate n different images
        cv2.line(blank_images[i], (y1[i], x[i,0]), (y2[i], x[i, 1]), (255,0,0), 2, cv2.LINE_AA)     # Draw lines with randomized coordinates
        if sign == '+':
            cv2.line(blank_images[i], (x[i,0], y1[i]), (x[i, 1], y2[i]), (255,0,0), 2, cv2.LINE_AA) # Draw lines with randomized coordinates
        if sign == '*':
            cv2.line(blank_images[i], (x[i,0], y1[i]), (x[i, 1], y2[i]), (255,0,0), 2, cv2.LINE_AA)
            # Rotate 45 degrees
            blank_images[i] = rotate(blank_images[i], -50, reshape=False)
            cv2.line(blank_images[i], (x[i,0], y1[i]), (x[i, 1], y2[i]), (255,0,0), 2, cv2.LINE_AA)
            blank_images[i] = rotate(blank_images[i], -50, reshape=False)
            cv2.line(blank_images[i], (x[i,0], y1[i]), (x[i, 1], y2[i]), (255,0,0), 2, cv2.LINE_AA)

    return blank_images

def show_generated(images, n=5):
    plt.figure(figsize=(2, 2))
    for i in range(n**2):
        plt.subplot(n, n, i+1)
        plt.axis('off')
        plt.imshow(images[i])
    plt.show()

show_generated(generate_images())
show_generated(generate_images(sign='+'))

def create_data(highest_integer, num_addends=2, operands=['+', '-']):
    """
    Creates the following data for all pairs of integers up to [1:highest integer][+/-][1:highest_integer]:

    @return:
    X_text: '51+21' -> text query of an arithmetic operation (5)
    X_img : Stack of MNIST images corresponding to the query (5 x 28 x 28) -> sequence of 5 images of size 28x28
    y_text: '72' -> answer of the arithmetic text query
    y_img :  Stack of MNIST images corresponding to the answer (3 x 28 x 28)

    Images for digits are picked randomly from the whole MNIST dataset.
    """

    num_indices = [np.where(MNIST_labels==x) for x in range(10)]
    num_data = [MNIST_data[inds] for inds in num_indices]
    image_mapping = dict(zip(unique_characters[:10], num_data))
    image_mapping['-'] = generate_images()
    image_mapping['+'] = generate_images(sign='+')
    image_mapping['*'] = generate_images(sign='*')
    image_mapping[' '] = np.zeros([1, 28, 28])

    X_text, X_img, y_text, y_img = [], [], [], []

    for i in range(highest_integer + 1):      # First addend
        for j in range(highest_integer + 1):  # Second addend
            for sign in operands: # Create all possible combinations of operands
                query_string = to_padded_chars(str(i) + sign + str(j), max_len=max_query_length, pad_right=True)
                query_image = []
                for n, char in enumerate(query_string):
                    image_set = image_mapping[char]
                    index = np.random.randint(0, len(image_set), 1)
                    query_image.append(image_set[index].squeeze())

                result = eval(query_string)
                result_string = to_padded_chars(result, max_len=max_answer_length, pad_right=True)
                result_image = []
                for n, char in enumerate(result_string):
                    image_set = image_mapping[char]
                    index = np.random.randint(0, len(image_set), 1)
                    result_image.append(image_set[index].squeeze())

                X_text.append(query_string)
                X_img.append(np.stack(query_image))
                y_text.append(result_string)
                y_img.append(np.stack(result_image))

    return np.stack(X_text), np.stack(X_img)/255., np.stack(y_text), np.stack(y_img)/255.

def to_padded_chars(integer, max_len=3, pad_right=False):
    """
    Returns a string of len()=max_len, containing the integer padded with ' ' on either right or left side
    """
    length = len(str(integer))
    padding = (max_len - length) * ' '
    if pad_right:
        return str(integer) + padding
    else:
        return padding + str(integer)

"""# Creating our data

The dataset consists of 20000 samples that (additions and subtractions between all 2-digit integers) and they have two kinds of inputs and label modalities:

  **X_text**: strings containing queries of length 5: ['  1+1  ', '11-18', ...]

  **X_image**: a stack of images representing a single query, dimensions: [5, 28, 28]

  **y_text**: strings containing answers of length 3: ['  2', '156']

  **y_image**: a stack of images that represents the answer to a query, dimensions: [3, 28, 28]
"""

# Illustrate the generated query/answer pairs

unique_characters = '0123456789+- '       # All unique characters that are used in the queries (13 in total: digits 0-9, 2 operands [+, -], and a space character ' '.)
highest_integer = 99                      # Highest value of integers contained in the queries

max_int_length = len(str(highest_integer))# Maximum number of characters in an integer
max_query_length = max_int_length * 2 + 1 # Maximum length of the query string (consists of two integers and an operand [e.g. '22+10'])
max_answer_length = 3    # Maximum length of the answer string (the longest resulting query string is ' 1-99'='-98')

# Create the data (might take around a minute)
(MNIST_data, MNIST_labels), _ = tf.keras.datasets.mnist.load_data()
X_text, X_img, y_text, y_img = create_data(highest_integer)
print(X_text.shape, X_img.shape, y_text.shape, y_img.shape)


## Display the samples that were created
def display_sample(n):
    labels = ['X_img:', 'y_img:']
    for i, data in enumerate([X_img, y_img]):
        plt.subplot(1,2,i+1)
        # plt.set_figheight(15)
        plt.axis('off')
        plt.title(labels[i])
        plt.imshow(np.hstack(data[n]), cmap='gray')
    print('='*50, f'\nQuery #{n}\n\nX_text: "{X_text[n]}" = y_text: "{y_text[n]}"')
    plt.show()

for _ in range(10):
    display_sample(np.random.randint(0, 10000, 1)[0])

"""## Helper functions

The functions below will help with input/output of the data.
"""

# One-hot encoding/decoding the text queries/answers so that they can be processed using RNNs
# You should use these functions to convert your strings and read out the output of your networks

def encode_labels(labels, max_len=3):
  n = len(labels)
  length = len(labels[0])
  char_map = dict(zip(unique_characters, range(len(unique_characters))))
  one_hot = np.zeros([n, length, len(unique_characters)])
  for i, label in enumerate(labels):
      m = np.zeros([length, len(unique_characters)])
      for j, char in enumerate(label):
          m[j, char_map[char]] = 1
      one_hot[i] = m

  return one_hot


def decode_labels(labels):
    pred = np.argmax(labels, axis=1)
    predicted = ''.join([unique_characters[i] for i in pred])

    return predicted

X_text_onehot = encode_labels(X_text)
y_text_onehot = encode_labels(y_text)

print(X_text_onehot.shape, y_text_onehot.shape)

"""---
---

## I. Text-to-text RNN model

The following code showcases how Recurrent Neural Networks (RNNs) are built using Keras. Several new layers are going to be used:

1. LSTM
2. TimeDistributed
3. RepeatVector

The code cell below explains each of these new components.

<img src="https://i.ibb.co/NY7FFTc/Screenshot-2023-11-10-at-09-27-25.png" alt="Screenshot-2023-11-10-at-09-27-25" border="0" width="500"></a>

"""

def build_text2text_model():

    # We start by initializing a sequential model
    text2text = tf.keras.Sequential()

    # "Encode" the input sequence using an RNN, producing an output of size 256.
    # In this case the size of our input vectors is [5, 13] as we have queries of length 5 and 13 unique characters. Each of these 5 elements in the query will be fed to the network one by one,
    # as shown in the image above (except with 5 elements).
    # Hint: In other applications, where your input sequences have a variable length (e.g. sentences), you would use input_shape=(None, unique_characters).
    text2text.add(LSTM(256, input_shape=(None, len(unique_characters))))

    # As the decoder RNN's input, repeatedly provide with the last output of RNN for each time step. Repeat 3 times as that's the maximum length of the output (e.g. '  1-99' = '-98')
    # when using 2-digit integers in queries. In other words, the RNN will always produce 3 characters as its output.
    text2text.add(RepeatVector(max_answer_length))

    # By setting return_sequences to True, return not only the last output but all the outputs so far in the form of (num_samples, timesteps, output_dim). This is necessary as TimeDistributed in the below expects
    # the first dimension to be the timesteps.
    text2text.add(LSTM(256, return_sequences=True))

    # Apply a dense layer to the every temporal slice of an input. For each of step of the output sequence, decide which character should be chosen.
    text2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))

    # Next we compile the model using categorical crossentropy as our loss function.
    text2text.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    text2text.summary()

    return text2text

"""Split: 25% test"""

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot, y_text_onehot, test_size=0.25, random_state=0)
text2text = build_text2text_model()
history=text2text.fit(X_train,y_train,epochs=10,batch_size=10, validation_split=0.1)
results25_accuracy = history.history['accuracy']
results25_loss = history.history['loss']
results25 = text2text.evaluate(X_test, y_test)
print("test loss, test acc:", results25)

predictions = text2text.predict(X_test)

decoded_predictions = [decode_labels(pred) for pred in predictions]
decoded_true_labels = [decode_labels(true) for true in y_test]

for i in range (predictions.shape[0]):
    if decoded_true_labels[i] != decoded_predictions[i]:
        print(f'Query: {decode_labels(X_test[i])} \nPrediction: {decoded_predictions[i]} \nTrue answer: {decoded_true_labels[i]} \n')

"""Split: 50% test"""

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot, y_text_onehot, test_size=0.5, random_state=0)
text2text = build_text2text_model()
history=text2text.fit(X_train,y_train,epochs=10,batch_size=10, validation_split=0.1)
results50_accuracy = history.history['accuracy']
results50_loss = history.history['loss']
results50 = text2text.evaluate(X_test, y_test)
print("test loss, test acc:", results50)

predictions = text2text.predict(X_test)

decoded_predictions = [decode_labels(pred) for pred in predictions]
decoded_true_labels = [decode_labels(true) for true in y_test]

for i in range (predictions.shape[0]):
    if decoded_true_labels[i] != decoded_predictions[i]:
        print(f'Query: {decode_labels(X_test[i])} \nPrediction: {decoded_predictions[i]} \nTrue answer: {decoded_true_labels[i]} \n')

"""Split: 75% test"""

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot, y_text_onehot, test_size=0.75, random_state=0)
text2text = build_text2text_model()
history=text2text.fit(X_train,y_train,epochs=10,batch_size=10,validation_split=0.1)
results75_accuracy = history.history['accuracy']
results75_loss = history.history['loss']
results75 = text2text.evaluate(X_test, y_test)
print("test loss, test acc:", results75)

predictions = text2text.predict(X_test)

decoded_predictions = [decode_labels(pred) for pred in predictions]
decoded_true_labels = [decode_labels(true) for true in y_test]
for i in range (predictions.shape[0]):
    if decoded_true_labels[i] != decoded_predictions[i]:
        print(f'Query: {decode_labels(X_test[i])} \nPrediction: {decoded_predictions[i]} \nTrue answer: {decoded_true_labels[i]} \n')

"""Split: 90% test"""

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot, y_text_onehot, test_size=0.90, random_state=0)
text2text = build_text2text_model()
history=text2text.fit(X_train,y_train,epochs=10,batch_size=10,validation_split=0.1)
results90_accuracy = history.history['accuracy']
results90_loss = history.history['loss']
results90 = text2text.evaluate(X_test, y_test)
print("test loss, test acc:", results90)

predictions = text2text.predict(X_test)

decoded_predictions = [decode_labels(pred) for pred in predictions]
decoded_true_labels = [decode_labels(true) for true in y_test]
for i in range (predictions.shape[0]):
    if decoded_true_labels[i] != decoded_predictions[i]:
        print(f'Query: {decode_labels(X_test[i])} \nPrediction: {decoded_predictions[i]} \nTrue answer: {decoded_true_labels[i]} \n')

"""Plot 1"""

plt.figure(figsize=(4,4))
plt.plot(results25_accuracy, label="test size=0.25")
plt.plot(results50_accuracy, label="test size=0.50")
plt.plot(results75_accuracy, label="test size=0.75")
plt.plot(results90_accuracy, label="test size=0.90")
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.savefig('text2text_accuracy.png', bbox_inches="tight")
plt.show()

plt.figure(figsize=(4,4))
plt.plot(results25_loss, label="test size=0.25")
plt.plot(results50_loss, label="test size=0.50")
plt.plot(results75_loss, label="test size=0.75")
plt.plot(results90_loss, label="test size=0.90")
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.savefig('text2text_loss.png', bbox_inches="tight")
plt.show()

"""Second text-to-text model with additional LSTM layers"""

def build_second_text2text_model():
    second_text2text = tf.keras.Sequential()
    second_text2text.add(LSTM(256, input_shape=(None, len(unique_characters)), return_sequences=True))
    second_text2text.add(LayerNormalization())
    second_text2text.add(LSTM(256,))
    second_text2text.add(RepeatVector(max_answer_length))

    second_text2text.add(LSTM(128,))
    second_text2text.add(LayerNormalization())

    second_text2text.add(RepeatVector(max_answer_length))

    second_text2text.add(LSTM(128, return_sequences=True))

    second_text2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))

    second_text2text.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    second_text2text.summary()

    return second_text2text

"""Split: 25% test"""

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot, y_text_onehot, test_size=0.25, random_state=0)
second_text2text = build_second_text2text_model()
history=second_text2text.fit(X_train,y_train,epochs=10,batch_size=10,validation_split=0.1)
second_results25_accuracy = history.history['accuracy']
second_results25_loss = history.history['loss']
second_results25 = second_text2text.evaluate(X_test, y_test)
print("test loss, test acc:", second_results25)

"""Split: 50% test"""

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot, y_text_onehot, test_size=0.50,random_state=0)
second_text2text = build_second_text2text_model()
history=second_text2text.fit(X_train,y_train,epochs=10,batch_size=10,validation_split=0.1)
second_results50_accuracy = history.history['accuracy']
second_results50_loss = history.history['loss']
second_results50 = second_text2text.evaluate(X_test, y_test)
print("test loss, test acc:", second_results50)

"""Split: 75% test"""

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot, y_text_onehot, test_size=0.75,random_state=0)
second_text2text = build_second_text2text_model()
history=second_text2text.fit(X_train,y_train,epochs=10,batch_size=10,validation_split=0.1)
second_results75_accuracy = history.history['accuracy']
second_results75_loss = history.history['loss']
second_results75 = second_text2text.evaluate(X_test, y_test)
print("test loss, test acc:", second_results75)

"""Split: 90% test"""

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot, y_text_onehot, test_size=0.90, random_state=0)
second_text2text = build_second_text2text_model()
history=second_text2text.fit(X_train,y_train,epochs=10,batch_size=10,validation_split=0.1)
second_results90_accuracy = history.history['accuracy']
second_results90_loss = history.history['loss']
second_results90 = second_text2text.evaluate(X_test, y_test)
print("test loss, test acc:", second_results90)

"""Plot 2"""

plt.figure(figsize=(4,4))
plt.plot(second_results25_accuracy, label="test size=0.25")
plt.plot(second_results50_accuracy, label="test size=0.50")
plt.plot(second_results75_accuracy, label="test size=0.75")
plt.plot(second_results90_accuracy, label="test size=0.90")
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.savefig('additional_text2text_accuracy.png', bbox_inches="tight")
plt.show()

plt.figure(figsize=(4,4))
plt.plot(second_results25_loss, label="test size=0.25")
plt.plot(second_results50_loss, label="test size=0.50")
plt.plot(second_results75_loss, label="test size=0.75")
plt.plot(second_results90_loss, label="test size=0.90")
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.savefig('additional_text2text_loss.png', bbox_inches="tight")
plt.show()

"""
---
---

## II. Image to text RNN Model

Hint: There are two ways of building the encoder for such a model - again by using the regular LSTM cells (with flattened images as vectors) or recurrect convolutional layers [ConvLSTM2D](https://keras.io/api/layers/recurrent_layers/conv_lstm2d/).

The goal here is to use **X_img** as inputs and **y_text** as outputs."""

X_train, X_test, y_train, y_test = train_test_split(X_img, y_text_onehot, test_size=0.25, random_state=0)

X_train_flatten = X_train.reshape(X_train.shape[0], X_train.shape[1],-1)
print(X_train_flatten.shape)
X_test_flatten = X_test.reshape(X_test.shape[0], X_test.shape[1], -1)
print(X_test_flatten.shape)

img2text = tf.keras.Sequential()

img2text.add(LSTM(256, input_shape=(None, 784)))
img2text.add(RepeatVector(max_answer_length))
img2text.add(LSTM(256, return_sequences=True))
img2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))
img2text.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
img2text.summary()

history=img2text.fit(X_train_flatten, y_train, epochs=25, batch_size=10,validation_split=0.1)
init_results_acc = history.history['accuracy']
init_results_loss = history.history['loss']
results1 = img2text.evaluate(X_test_flatten, y_test)
print("test loss, test acc:", results1)

"""one-extra layer"""

X_train, X_test, y_train, y_test = train_test_split(X_img, y_text_onehot, test_size=0.25, random_state=0)

X_train_flatten = X_train.reshape(X_train.shape[0], X_train.shape[1],-1)
print(X_train_flatten.shape)
X_test_flatten = X_test.reshape(X_test.shape[0], X_test.shape[1], -1)
print(X_test_flatten.shape)

second_img2text = tf.keras.Sequential()

second_img2text.add(LSTM(256, input_shape=(None, 784), return_sequences=True))
second_img2text.add(LSTM(256,))
second_img2text.add(RepeatVector(max_answer_length))
second_img2text.add(LSTM(256, return_sequences=True))

second_img2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))

second_img2text.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
second_img2text.summary()

history=second_img2text.fit(X_train_flatten, y_train, epochs=25, batch_size=10,validation_split=0.1)
one_results_acc = history.history['accuracy']
one_results_loss = history.history['loss']
results2 = second_img2text.evaluate(X_test_flatten, y_test)
print("test loss, test acc:", results2)

"""two-extra layers"""

X_train, X_test, y_train, y_test = train_test_split(X_img, y_text_onehot, test_size=0.25, random_state=0)

X_train_flatten = X_train.reshape(X_train.shape[0], X_train.shape[1],-1)
print(X_train_flatten.shape)
X_test_flatten = X_test.reshape(X_test.shape[0], X_test.shape[1], -1)
print(X_test_flatten.shape)

second_img2text = tf.keras.Sequential()

second_img2text.add(LSTM(256, input_shape=(None, 784), return_sequences=True))
second_img2text.add(LSTM(256, return_sequences=True))
second_img2text.add(LSTM(256,))
second_img2text.add(RepeatVector(max_answer_length))
second_img2text.add(LSTM(256, return_sequences=True))
second_img2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))

second_img2text.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
second_img2text.summary()

history=second_img2text.fit(X_train_flatten, y_train, epochs=25, batch_size=10,validation_split=0.1)
two_results_acc = history.history['accuracy']
two_results_loss = history.history['loss']
results3 = second_img2text.evaluate(X_test_flatten, y_test)
print("test loss, test acc:", results3)

"""Plot 3"""

plt.figure(figsize=(4,4))
plt.plot(init_results_acc, label="Initial network")
plt.plot(one_results_acc, label="One additional LSTM layer")
plt.plot(two_results_acc, label="Two additional LSTM layers")

plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.savefig('img2text_acc.png', bbox_inches="tight")
plt.show()

plt.figure(figsize=(4,4))
plt.plot(init_results_loss, label="Initial network")
plt.plot(one_results_loss, label="One additional LSTM layer")
plt.plot(two_results_loss, label="Two additional LSTM layers")

plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.savefig('imgttext_loss.png', bbox_inches="tight")
plt.show()

"""---
---

## III. Text to image RNN Model

Hint: to make this model work really well you could use deconvolutional layers in your decoder (you might need to look up ***Conv2DTranspose*** layer). However, regular vector-based decoder will work as well.

The goal here is to use **X_text** as inputs and **y_img** as outputs.
"""

# import numpy as np

# unique_values = np.unique(y_img)
# print(unique_values)

# univalues = np.unique(X_text_onehot)
# print(univalues)

y_img.shape[1:][1]

"""# Initial Model: Text-to-image"""

text2image = Sequential()

# Encoder
text2image.add(LSTM(512, input_shape=(max_query_length, len(unique_characters))))
text2image.add(LayerNormalization())

# Repeat the vector for decoding
text2image.add(RepeatVector(max_answer_length))

# Decoder
text2image.add(LSTM(512, return_sequences=True))
text2image.add(LayerNormalization())

# TimeDistributed layer for Dense
text2image.add(TimeDistributed(Dense((28 * 28), activation='softmax')))
text2image.add(LayerNormalization())

text2image.add(Reshape((max_answer_length, 28, 28)))

# Conv2DTranspose layers
text2image.add(Conv2DTranspose(128, (3, 3), padding='same', activation='relu'))
text2image.add(BatchNormalization())

text2image.add(Conv2DTranspose(64, (3, 3), padding='same', activation='relu'))
text2image.add(BatchNormalization())

text2image.add(Conv2DTranspose(28, (3, 3), padding='same', activation='sigmoid'))  # black and white images




text2image.compile(loss='mean_squared_error', optimizer='adam', metrics=['mse', 'mean_absolute_error'])

X_text_train, X_text_test, y_img_train, y_img_test = train_test_split(X_text_onehot, y_img, test_size=0.25, random_state=0)

text_to_img_history = text2image.fit(X_text_train, y_img_train, epochs=20, batch_size=28, validation_data=(X_text_test, y_img_test))

text_to_img_results = text2image.evaluate(X_text_test, y_img_test)
print("Test loss, test mse, test mae:", text_to_img_results)

# fuction for visualizing generated images
def generate_images_from_text(model, text_query):
    text_query_onehot = encode_labels([text_query])
    predicted_images = model.predict(text_query_onehot)
    return predicted_images.squeeze()

text_query1 = '24+59'
generated_images = generate_images_from_text(text2image, text_query1)

generated_images = generated_images * 255.0


plt.figure(figsize=(10, 5))
for i in range(generated_images.shape[0]):
    plt.subplot(1, generated_images.shape[0], i + 1)
    plt.imshow(generated_images[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query2 = '26-59'
generated_images1 = generate_images_from_text(text2image, text_query2)

generated_images1 = generated_images1 * 255.0


plt.figure(figsize=(10, 5))
for i in range(generated_images1.shape[0]):
    plt.subplot(1, generated_images1.shape[0], i + 1)
    plt.imshow(generated_images1[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query3 = '89+56'
generated_images2 = generate_images_from_text(text2image, text_query3)

generated_images2 = generated_images2 * 255.0


plt.figure(figsize=(10, 5))
for i in range(generated_images2.shape[0]):
    plt.subplot(1, generated_images2.shape[0], i + 1)
    plt.imshow(generated_images2[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

"""# Add additional LSTM layers to your encoder networks - Text-to-image network

## Adding one extra LSTM layer in the encoder - 512 units
"""

text2image2 = Sequential()

# First LSTM layer with return_sequences=True
text2image2.add(LSTM(512, input_shape=(max_query_length, len(unique_characters)), return_sequences=True))
text2image2.add(LayerNormalization())

# Second LSTM layer
text2image2.add(LSTM(512, return_sequences=False))
text2image2.add(LayerNormalization())

# Repeat the vector for decoding
text2image2.add(RepeatVector(max_answer_length))

# The rest of your model remains the same
text2image2.add(LSTM(512, return_sequences=True))
text2image2.add(LayerNormalization())

text2image2.add(TimeDistributed(Dense((28 * 28), activation='softmax')))
text2image2.add(LayerNormalization())

text2image2.add(Reshape((max_answer_length, 28, 28)))

text2image2.add(Conv2DTranspose(128, (3, 3), padding='same', activation='relu'))
text2image2.add(BatchNormalization())

text2image2.add(Conv2DTranspose(64, (3, 3), padding='same', activation='relu'))
text2image2.add(BatchNormalization())

text2image2.add(Conv2DTranspose(28, (3, 3), padding='same', activation='sigmoid'))

text2image2.compile(loss='mean_squared_error', optimizer='adam', metrics=['mse', 'mean_absolute_error'])



X_text_train, X_text_test, y_img_train, y_img_test = train_test_split(X_text_onehot, y_img, test_size=0.25, random_state=0)

text_to_img_history2 = text2image2.fit(X_text_train, y_img_train, epochs=20, batch_size=28, validation_data=(X_text_test, y_img_test))

text_to_img_results2 = text2image2.evaluate(X_text_test, y_img_test)
print("Test loss, test mse, test mae:", text_to_img_results2)

text_query1 = '24+59'
generated_images3 = generate_images_from_text(text2image2, text_query1)

generated_images3 = generated_images3 * 255.0


plt.figure(figsize=(10, 5))
for i in range(generated_images3.shape[0]):
    plt.subplot(1, generated_images3.shape[0], i + 1)
    plt.imshow(generated_images3[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query2 = '26-59'
generated_images4 = generate_images_from_text(text2image2, text_query2)

generated_images4 = generated_images4 * 255.0


plt.figure(figsize=(10, 5))
for i in range(generated_images4.shape[0]):
    plt.subplot(1, generated_images4.shape[0], i + 1)
    plt.imshow(generated_images4[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query3 = '89+56'
generated_images5 = generate_images_from_text(text2image2, text_query3)

generated_images5= generated_images5 * 255.0


plt.figure(figsize=(10, 5))
for i in range(generated_images5.shape[0]):
    plt.subplot(1, generated_images5.shape[0], i + 1)
    plt.imshow(generated_images5[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

"""## Adding one extra LSTM layer in the encoder - 256 units"""

text2image3 = Sequential()

# First LSTM layer with return_sequences=True
text2image3.add(LSTM(512, input_shape=(max_query_length, len(unique_characters)), return_sequences=True))
text2image3.add(LayerNormalization())

# second LSTM layer with return_sequences=False - 256 units
text2image3.add(LSTM(256, return_sequences=False))
text2image3.add(LayerNormalization())

# Decoder
text2image3.add(RepeatVector(max_answer_length))

text2image3.add(LSTM(512, return_sequences=True))
text2image3.add(LayerNormalization())

text2image3.add(TimeDistributed(Dense((28 * 28), activation='softmax')))
text2image3.add(LayerNormalization())

text2image3.add(Reshape((max_answer_length, 28, 28)))

text2image3.add(Conv2DTranspose(128, (3, 3), padding='same', activation='relu'))
text2image3.add(BatchNormalization())

text2image3.add(Conv2DTranspose(64, (3, 3), padding='same', activation='relu'))
text2image3.add(BatchNormalization())

text2image3.add(Conv2DTranspose(28, (3, 3), padding='same', activation='sigmoid'))

text2image3.compile(loss='mean_squared_error', optimizer='adam', metrics=['mse', 'mean_absolute_error'])



X_text_train, X_text_test, y_img_train, y_img_test = train_test_split(X_text_onehot, y_img, test_size=0.25, random_state=0)


text_to_img_history3 = text2image3.fit(X_text_train, y_img_train, epochs=20, batch_size=28,
                                       validation_data=(X_text_test, y_img_test))

text_to_img_results3 = text2image3.evaluate(X_text_test, y_img_test)
print("Test loss, test mse, test mae:", text_to_img_results3)

text_query1 = '24+59'
generated_images6 = generate_images_from_text(text2image3, text_query1)

generated_images6 = generated_images6 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images6.shape[0]):
    plt.subplot(1, generated_images6.shape[0], i + 1)
    plt.imshow(generated_images6[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query2 = '26-59'
generated_images7 = generate_images_from_text(text2image3, text_query2)

generated_images7 = generated_images7 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images7.shape[0]):
    plt.subplot(1, generated_images7.shape[0], i + 1)
    plt.imshow(generated_images7[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query3 = '89+56'
generated_images8 = generate_images_from_text(text2image3, text_query3)

generated_images8 = generated_images8 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images8.shape[0]):
    plt.subplot(1, generated_images8.shape[0], i + 1)
    plt.imshow(generated_images8[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

"""## Adding two extra LSTM layer in the encoder - both 512 units"""

text2image4 = Sequential()

# First LSTM layer with return_sequences=True
text2image4.add(LSTM(512, input_shape=(max_query_length, len(unique_characters)), return_sequences=True))
text2image4.add(LayerNormalization())

# Second LSTM layer
text2image4.add(LSTM(512, return_sequences=True))
text2image4.add(LayerNormalization())

text2image4.add(LSTM(512, return_sequences=False))
text2image4.add(LayerNormalization())

# Repeat the vector for decoding
text2image4.add(RepeatVector(max_answer_length))

# The rest of the model remains the same
text2image4.add(LSTM(512, return_sequences=True))
text2image4.add(LayerNormalization())

text2image4.add(TimeDistributed(Dense((28 * 28), activation='softmax')))
text2image4.add(LayerNormalization())

text2image4.add(Reshape((max_answer_length, 28, 28)))

text2image4.add(Conv2DTranspose(128, (3, 3), padding='same', activation='relu'))
text2image4.add(BatchNormalization())

text2image4.add(Conv2DTranspose(64, (3, 3), padding='same', activation='relu'))
text2image4.add(BatchNormalization())

text2image4.add(Conv2DTranspose(28, (3, 3), padding='same', activation='sigmoid'))


text2image4.compile(loss='mean_squared_error', optimizer='adam', metrics=['mse', 'mean_absolute_error'])


X_text_train, X_text_test, y_img_train, y_img_test = train_test_split(X_text_onehot, y_img, test_size=0.25, random_state=0)

text_to_img_history4 = text2image4.fit(X_text_train, y_img_train, epochs=20, batch_size=28, validation_data=(X_text_test, y_img_test))

text_to_img_results4 = text2image4.evaluate(X_text_test, y_img_test)
print("Test loss, test mse, test mae:", text_to_img_results4)

text_query1 = '24+59'
generated_images9 = generate_images_from_text(text2image4, text_query1)

generated_images9 = generated_images9 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images9.shape[0]):
    plt.subplot(1, generated_images9.shape[0], i + 1)
    plt.imshow(generated_images9[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query2 = '26-59'
generated_images10 = generate_images_from_text(text2image4, text_query2)

generated_images10 = generated_images10 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images10.shape[0]):
    plt.subplot(1, generated_images10.shape[0], i + 1)
    plt.imshow(generated_images10[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query3 = '89+56'
generated_images11 = generate_images_from_text(text2image4, text_query3)

generated_images11 = generated_images11 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images11.shape[0]):
    plt.subplot(1, generated_images11.shape[0], i + 1)
    plt.imshow(generated_images11[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

"""## Adding two extra LSTM layer in the encoder - 256 and 128 units"""

text2image5 = Sequential()

# First LSTM layer with return_sequences=True
text2image5.add(LSTM(512, input_shape=(max_query_length, len(unique_characters)), return_sequences=True))
text2image5.add(LayerNormalization())

# Second LSTM layer
text2image5.add(LSTM(256, return_sequences=True))
text2image5.add(LayerNormalization())

text2image5.add(LSTM(128, return_sequences=False))
text2image5.add(LayerNormalization())

# Repeat the vector for decoding
text2image5.add(RepeatVector(max_answer_length))

# The rest of the model remains the same
text2image5.add(LSTM(512, return_sequences=True))
text2image5.add(LayerNormalization())

text2image5.add(TimeDistributed(Dense((28 * 28), activation='softmax')))
text2image5.add(LayerNormalization())

text2image5.add(Reshape((max_answer_length, 28, 28)))

text2image5.add(Conv2DTranspose(128, (3, 3), padding='same', activation='relu'))
text2image5.add(BatchNormalization())

text2image5.add(Conv2DTranspose(64, (3, 3), padding='same', activation='relu'))
text2image5.add(BatchNormalization())

text2image5.add(Conv2DTranspose(28, (3, 3), padding='same', activation='sigmoid'))


text2image5.compile(loss='mean_squared_error', optimizer='adam', metrics=['mse', 'mean_absolute_error'])


X_text_train, X_text_test, y_img_train, y_img_test = train_test_split(X_text_onehot, y_img, test_size=0.25, random_state=0)

text_to_img_history5 = text2image5.fit(X_text_train, y_img_train, epochs=20, batch_size=28, validation_data=(X_text_test, y_img_test))

text_to_img_results5 = text2image5.evaluate(X_text_test, y_img_test)
print("Test loss, test mse, test mae:", text_to_img_results5)

text_query1 = '24+59'
generated_images12 = generate_images_from_text(text2image5, text_query1)

generated_images12 = generated_images12 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images12.shape[0]):
    plt.subplot(1, generated_images12.shape[0], i + 1)
    plt.imshow(generated_images12[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query2 = '26-59'
generated_images13 = generate_images_from_text(text2image5, text_query2)

generated_images13 = generated_images13 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images13.shape[0]):
    plt.subplot(1, generated_images13.shape[0], i + 1)
    plt.imshow(generated_images13[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query3 = '89+56'
generated_images14 = generate_images_from_text(text2image5, text_query3)

generated_images14 = generated_images14 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images14.shape[0]):
    plt.subplot(1, generated_images14.shape[0], i + 1)
    plt.imshow(generated_images14[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

"""## More epoch (= 50) for image appearance improvement

### Basic Model
"""

text2image_50 = Sequential()

# Encoder
text2image_50.add(LSTM(512, input_shape=(max_query_length, len(unique_characters))))
text2image_50.add(LayerNormalization())

# Repeat the vector for decoding
text2image_50.add(RepeatVector(max_answer_length))

# Decoder
text2image_50.add(LSTM(512, return_sequences=True))
text2image_50.add(LayerNormalization())

# TimeDistributed layer for Dense
text2image_50.add(TimeDistributed(Dense((28 * 28), activation='softmax')))
text2image_50.add(LayerNormalization())

text2image_50.add(Reshape((max_answer_length, 28, 28)))

# Conv2DTranspose layers
text2image_50.add(Conv2DTranspose(128, (3, 3), padding='same', activation='relu'))
text2image_50.add(BatchNormalization())

text2image_50.add(Conv2DTranspose(64, (3, 3), padding='same', activation='relu'))
text2image_50.add(BatchNormalization())

text2image_50.add(Conv2DTranspose(28, (3, 3), padding='same', activation='sigmoid'))  # black and white images


text2image_50.compile(loss='mean_squared_error', optimizer='adam', metrics=['mse', 'mean_absolute_error'])


X_text_train, X_text_test, y_img_train, y_img_test = train_test_split(X_text_onehot, y_img, test_size=0.25, random_state=0)


text_to_img_history_50 = text2image_50.fit(X_text_train, y_img_train, epochs=50, batch_size=28, validation_data=(X_text_test, y_img_test))

text_to_img_results_50 = text2image_50.evaluate(X_text_test, y_img_test)
print("Test loss, test mse, test mae:", text_to_img_results_50)

text_query1 = '24+59'
generated_images15 = generate_images_from_text(text2image_50, text_query1)


generated_images15 = generated_images15 * 255.0


plt.figure(figsize=(10, 5))
for i in range(generated_images15.shape[0]):
    plt.subplot(1, generated_images15.shape[0], i + 1)
    plt.imshow(generated_images15[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query2 = '26-59'

generated_images16 = generate_images_from_text(text2image_50, text_query2)

generated_images16 = generated_images16 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images16.shape[0]):
    plt.subplot(1, generated_images16.shape[0], i + 1)
    plt.imshow(generated_images16[i].astype(int), cmap='gray')  # Adjust cmap if needed
    plt.axis('off')
plt.show()

text_query3 = '89+56'
generated_images17 = generate_images_from_text(text2image_50, text_query3)

generated_images17 = generated_images17 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images17.shape[0]):
    plt.subplot(1, generated_images17.shape[0], i + 1)
    plt.imshow(generated_images17[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

"""### One extra LSTM layer - 256 units - 50 epoch"""

text2image3_50 = Sequential()

# First LSTM layer with return_sequences=True
text2image3_50.add(LSTM(512, input_shape=(max_query_length, len(unique_characters)), return_sequences=True))
text2image3_50.add(LayerNormalization())

# Second LSTM layer
text2image3_50.add(LSTM(256, return_sequences=False))
text2image3_50.add(LayerNormalization())

# Repeat the vector for decoding
text2image3_50.add(RepeatVector(max_answer_length))

# The rest of the model remains the same
text2image3_50.add(LSTM(512, return_sequences=True))
text2image3_50.add(LayerNormalization())

text2image3_50.add(TimeDistributed(Dense((28 * 28), activation='softmax')))
text2image3_50.add(LayerNormalization())

text2image3_50.add(Reshape((max_answer_length, 28, 28)))

text2image3_50.add(Conv2DTranspose(128, (3, 3), padding='same', activation='relu'))
text2image3_50.add(BatchNormalization())

text2image3_50.add(Conv2DTranspose(64, (3, 3), padding='same', activation='relu'))
text2image3_50.add(BatchNormalization())

text2image3_50.add(Conv2DTranspose(28, (3, 3), padding='same', activation='sigmoid'))


text2image3_50.compile(loss='mean_squared_error', optimizer='adam', metrics=['mse', 'mean_absolute_error'])


X_text_train, X_text_test, y_img_train, y_img_test = train_test_split(X_text_onehot, y_img, test_size=0.25, random_state=0)

text_to_img_history3_50 = text2image3_50.fit(X_text_train, y_img_train, epochs=50, batch_size=28, validation_data=(X_text_test, y_img_test))

text_to_img_results3_50 = text2image3_50.evaluate(X_text_test, y_img_test)
print("Test loss, test mse, test mae:", text_to_img_results3_50)

text_query1 = '24+59'
generated_images18 = generate_images_from_text(text2image3_50, text_query1)

generated_images18 = generated_images18 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images18.shape[0]):
    plt.subplot(1, generated_images18.shape[0], i + 1)
    plt.imshow(generated_images18[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query2 = '26-59'
generated_images19 = generate_images_from_text(text2image3_50, text_query2)

generated_images19 = generated_images19 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images19.shape[0]):
    plt.subplot(1, generated_images19.shape[0], i + 1)
    plt.imshow(generated_images19[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query3 = '89+56'
generated_images20 = generate_images_from_text(text2image3_50, text_query3)

generated_images20 = generated_images20 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images20.shape[0]):
    plt.subplot(1, generated_images20.shape[0], i + 1)
    plt.imshow(generated_images20[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

"""### Two extra LSTM layers - both 512 units - 50 epoch"""

text2image4_50 = Sequential()

# First LSTM layer with return_sequences=True
text2image4_50.add(LSTM(512, input_shape=(max_query_length, len(unique_characters)), return_sequences=True))
text2image4_50.add(LayerNormalization())

# Second LSTM layer
text2image4_50.add(LSTM(512, return_sequences=True))
text2image4_50.add(LayerNormalization())

text2image4_50.add(LSTM(512, return_sequences=False))
text2image4_50.add(LayerNormalization())

# Repeat the vector for decoding
text2image4_50.add(RepeatVector(max_answer_length))

# The rest of the model remains the same
text2image4_50.add(LSTM(512, return_sequences=True))
text2image4_50.add(LayerNormalization())

text2image4_50.add(TimeDistributed(Dense((28 * 28), activation='softmax')))
text2image4_50.add(LayerNormalization())

text2image4_50.add(Reshape((max_answer_length, 28, 28)))

text2image4_50.add(Conv2DTranspose(128, (3, 3), padding='same', activation='relu'))
text2image4_50.add(BatchNormalization())

text2image4_50.add(Conv2DTranspose(64, (3, 3), padding='same', activation='relu'))
text2image4_50.add(BatchNormalization())

text2image4_50.add(Conv2DTranspose(28, (3, 3), padding='same', activation='sigmoid'))


text2image4_50.compile(loss='mean_squared_error', optimizer='adam', metrics=['mse', 'mean_absolute_error'])


X_text_train, X_text_test, y_img_train, y_img_test = train_test_split(X_text_onehot, y_img, test_size=0.25, random_state=0)

text_to_img_history4_50 = text2image4_50.fit(X_text_train, y_img_train, epochs=50, batch_size=28, validation_data=(X_text_test, y_img_test))

text_to_img_results4_50 = text2image4_50.evaluate(X_text_test, y_img_test)
print("Test loss, test mse, test mae:", text_to_img_results4_50)

text_query1 = '24+59'
generated_images21 = generate_images_from_text(text2image4_50, text_query1)

generated_images21 = generated_images21 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images21.shape[0]):
    plt.subplot(1, generated_images21.shape[0], i + 1)
    plt.imshow(generated_images21[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query2 = '26-59'
generated_images22 = generate_images_from_text(text2image4_50, text_query2)

generated_images22 = generated_images22 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images22.shape[0]):
    plt.subplot(1, generated_images22.shape[0], i + 1)
    plt.imshow(generated_images22[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

text_query3 = '89+56'
generated_images23 = generate_images_from_text(text2image4_50, text_query3)

generated_images23 = generated_images23 * 255.0

plt.figure(figsize=(10, 5))
for i in range(generated_images23.shape[0]):
    plt.subplot(1, generated_images23.shape[0], i + 1)
    plt.imshow(generated_images23[i].astype(int), cmap='gray')
    plt.axis('off')
plt.show()

"""
---
---
---

# Part 2: Multiplication
The cell below will create the multiplication dataset used in this part of the assignment."""

# Illustrate the generated query/answer pairs

unique_characters = '0123456789* '       # All unique characters that are used in the queries (13 in total: digits 0-9, 2 operands [+, -], and a space character ' '.)
highest_integer = 99                      # Highest value of integers contained in the queries

max_int_length = len(str(highest_integer))# Maximum number of characters in an integer
max_query_length = max_int_length * 2 + 1 # Maximum length of the query string (consists of two integers and an operand [e.g. '22+10'])
max_answer_length = 5    # Maximum length of the answer string (the longest resulting query string is ' 99*(-99)'='-9801')

# Create the data (might take around a minute)
(MNIST_data, MNIST_labels), _ = tf.keras.datasets.mnist.load_data()
X_text, X_img, y_text, y_img = create_data(highest_integer, operands=['*'])
print(X_text.shape, X_img.shape, y_text.shape, y_img.shape)


## Display the samples that were created
def display_sample(n):
    labels = ['X_img:', 'y_img:']
    for i, data in enumerate([X_img, y_img]):
        plt.subplot(1,2,i+1)
        # plt.set_figheight(15)
        plt.axis('off')
        plt.title(labels[i])
        plt.imshow(np.hstack(data[n]), cmap='gray')
    print('='*50, f'\nQuery #{n}\n\nX_text: "{X_text[n]}" = y_text: "{y_text[n]}"')
    plt.show()

for _ in range(10):
    display_sample(np.random.randint(0, 10000, 1)[0])

"""Helper functions"""

def encode_labels(labels, max_len=3):
  n = len(labels)
  length = len(labels[0])
  char_map = dict(zip(unique_characters, range(len(unique_characters))))
  one_hot = np.zeros([n, length, len(unique_characters)])
  for i, label in enumerate(labels):
      m = np.zeros([length, len(unique_characters)])
      for j, char in enumerate(label):
          m[j, char_map[char]] = 1
      one_hot[i] = m

  return one_hot


def decode_labels(labels):
    pred = np.argmax(labels, axis=1)
    predicted = ''.join([unique_characters[i] for i in pred])

    return predicted

X_text_onehot_m = encode_labels(X_text)
y_text_onehot_m = encode_labels(y_text)

print(X_text_onehot_m.shape, y_text_onehot_m.shape)

"""Text-to-text RNN Model for multiplication"""

def build_text2text_model_multiplication():

    # We start by initializing a sequential model
    text2text = tf.keras.Sequential()

    # "Encode" the input sequence using an RNN, producing an output of size 256.
    # In this case the size of our input vectors is [5, 13] as we have queries of length 5 and 13 unique characters. Each of these 5 elements in the query will be fed to the network one by one,
    # as shown in the image above (except with 5 elements).
    # Hint: In other applications, where your input sequences have a variable length (e.g. sentences), you would use input_shape=(None, unique_characters).
    text2text.add(LSTM(256, input_shape=(None, len(unique_characters))))

    # As the decoder RNN's input, repeatedly provide with the last output of RNN for each time step. Repeat 3 times as that's the maximum length of the output (e.g. '  1-99' = '-98')
    # when using 2-digit integers in queries. In other words, the RNN will always produce 3 characters as its output.
    text2text.add(RepeatVector(max_answer_length))

    # By setting return_sequences to True, return not only the last output but all the outputs so far in the form of (num_samples, timesteps, output_dim). This is necessary as TimeDistributed in the below expects
    # the first dimension to be the timesteps.
    text2text.add(LSTM(256, return_sequences=True))

    # Apply a dense layer to the every temporal slice of an input. For each of step of the output sequence, decide which character should be chosen.
    text2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))

    # Next we compile the model using categorical crossentropy as our loss function.
    text2text.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    text2text.summary()

    return text2text

"""#### Split 50% train 50% test"""

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot_m, y_text_onehot_m, test_size=0.5, random_state=0)
text2text_m = build_text2text_model_multiplication()
history_m=text2text_m.fit(X_train,y_train,epochs=20,batch_size=10,validation_split=0.1)
results_m = text2text_m.evaluate(X_test, y_test)
print("test loss, test acc:", results_m)

"""#### Split 75% trai 25% test"""

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot_m, y_text_onehot_m, test_size=0.1, random_state=0)
text2text_m1 = build_text2text_model_multiplication()
history_m1=text2text_m1.fit(X_train,y_train,epochs=20,batch_size=10,validation_split=0.1)
results_m1 = text2text_m1.evaluate(X_test, y_test)
print("test loss, test acc:", results_m1)

"""#### Split 90% train 10% test"""

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot_m, y_text_onehot_m, test_size=0.1, random_state=0)
text2text_m2 = build_text2text_model_multiplication()
history_m2=text2text_m2.fit(X_train,y_train,epochs=20,batch_size=10,validation_split=0.1)
results_m2 = text2text_m2.evaluate(X_test, y_test)
print("test loss, test acc:", results_m2)

predictions_m = text2text_m.predict(X_test)

decoded_predictions_m = [decode_labels(pred) for pred in predictions_m]
decoded_true_labels_m = [decode_labels(true) for true in y_test]

# count = 0
for i in range (20):
    num=random.randint(1, len(decoded_predictions_m))
    print(f'Query: {decode_labels(X_test[num])} \nPrediction: {decoded_predictions_m[num]} \nTrue answer: {decoded_true_labels_m[num]} \n')
    # if decoded_true_labels_m[i] != decoded_predictions_m[i]:
    #     count += 1

# Create DataFrames from the training history for both models
df_history_im = pd.DataFrame(history_m.history)  # Fix: Correct variable name
df_history_im1 = pd.DataFrame(history_m1.history)
df_history_im2 = pd.DataFrame(history_m2.history)

# Define custom labels for the legend
legend_labels = ["Accuracy test size: 0.50 ", "Validation Accuracy test size: 0.50 ",
                 "Accuracy test size: 0.25", "Validation Accuracy test size: 0.25",
                 "Accuracy test size: 0.10", "Validation Accuracy test size: 0.10"]

# Plot only accuracy and validation accuracy for both models with custom labels
ax = df_history_im.plot(figsize=(8, 5), grid=True, xlabel="Epoch",
                         y=["accuracy", "val_accuracy"],
                         style={"accuracy": "b-", "val_accuracy": "b--*"},
                         title='RNNs MNIST multiplication text-to-text accuracy')

df_history_im1.plot(ax=ax, y=["accuracy", "val_accuracy"],
                    style={"accuracy": "m-", "val_accuracy": "m--*"})
df_history_im2.plot(ax=ax, y=["accuracy", "val_accuracy"],
                    style={"accuracy": "r-", "val_accuracy": "r--*"})

# Show the legend with the custom labels
ax.legend(legend_labels)

# Show the plot
plt.show()

ax = df_history_im.plot(figsize=(8, 5), grid=True, xlabel="Epoch",
                         y=["loss", "val_loss"],
                         style={"loss": "b-", "val_loss": "b--*"},
                         title='RNNs MNIST multiplication text-to-text loss')

df_history_im1.plot(ax=ax, y=["loss", "val_loss"],
                    style={"loss": "m-", "val_loss": "m--*"})
df_history_im2.plot(ax=ax, y=["loss", "val_loss"],
                    style={"loss": "r-", "val_loss": "r--*"})

# Show the legend with the custom labels
ax.legend(legend_labels)

# Show the plot
plt.show()

"""#### Add layers text to text"""

def build_text2text_model_multiplication_layers():
    drop_out_rate = 0.2

    text2text = tf.keras.Sequential()
    text2text.add(LSTM(512, input_shape=(None, len(unique_characters)), return_sequences=True))

    text2text.add(LayerNormalization())
    text2text.add(LSTM(512,))
    text2text.add(LayerNormalization())
    text2text.add(Dropout(drop_out_rate))

    text2text.add(RepeatVector(max_answer_length))

    text2text.add(LSTM(512, return_sequences=True))

    text2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))

    #optimizer = Adam(learning_rate=0.001, clipnorm=1.0)
    text2text.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    text2text.summary()

    return text2text

early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot_m, y_text_onehot_m, test_size=0.1, random_state=0)
text2text_m1 = build_text2text_model_multiplication_layers()

history_m1=text2text_m1.fit(X_train,y_train,epochs=10,batch_size=10,validation_split=0.1,callbacks=[early_stopping]) #batch size 32
results_m1 = text2text_m1.evaluate(X_test, y_test)
print("test loss, test acc:", results_m1)

def build_text2text_model_multiplication_layers2():
    drop_out_rate = 0.2

    text2text = tf.keras.Sequential()
    text2text.add(LSTM(512, input_shape=(None, len(unique_characters)), return_sequences=True))


    text2text.add(LSTM(512,return_sequences=True))
    text2text.add(LayerNormalization())
    text2text.add(Dropout(drop_out_rate))
    text2text.add(LSTM(512,))


    text2text.add(RepeatVector(max_answer_length))

    text2text.add(LSTM(512, return_sequences=True))

    text2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))

    #optimizer = Adam(learning_rate=0.001, clipnorm=1.0)
    text2text.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    text2text.summary()

    return text2text

early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot_m, y_text_onehot_m, test_size=0.1, random_state=0)
text2text_l2 = build_text2text_model_multiplication_layers2()

history_l2=text2text_l2.fit(X_train,y_train,epochs=10,batch_size=10,validation_split=0.1,callbacks=[early_stopping]) #batch size 32
results_l2 = text2text_l2.evaluate(X_test, y_test)
print("test loss, test acc:", results_l2)

def build_text2text_model_multiplication_layers_():
    drop_out_rate = 0.25

    text2text = tf.keras.Sequential()
    text2text.add(LSTM(512, input_shape=(None, len(unique_characters)), return_sequences=True))

    text2text.add(LayerNormalization())
    text2text.add(LSTM(512,))
    text2text.add(LayerNormalization())
    text2text.add(Dropout(drop_out_rate))

    text2text.add(RepeatVector(max_answer_length))

    text2text.add(LSTM(256, return_sequences=True))

    text2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))

    optimizer = Adam(learning_rate=0.001, clipnorm=1.0)
    text2text.compile(loss='categorical_crossentropy', optimizer= optimizer, metrics=['accuracy'])
    text2text.summary()

    return text2text

early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot_m, y_text_onehot_m, test_size=0.1, random_state=0)
text2text_l3 = build_text2text_model_multiplication_layers_()

history_l3=text2text_l3.fit(X_train,y_train,epochs=10,batch_size=10,validation_split=0.1,callbacks=[early_stopping])
results_l3 = text2text_l3.evaluate(X_test, y_test)
print("test loss, test acc:", results_l3)

def build_text2text_model_multiplication_layers_best():
    drop_out_rate = 0.25

    text2text = tf.keras.Sequential()
    text2text.add(LSTM(256, input_shape=(None, len(unique_characters)), return_sequences=True))

    text2text.add(LayerNormalization())
    text2text.add(LSTM(256,))
    text2text.add(LayerNormalization())
    text2text.add(Dropout(drop_out_rate))

    text2text.add(RepeatVector(max_answer_length))

    text2text.add(LSTM(512, return_sequences=True))

    text2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))


    text2text.compile(loss='categorical_crossentropy', optimizer= 'adam', metrics=['accuracy'])
    text2text.summary()

    return text2text

early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

X_train, X_test, y_train, y_test = train_test_split(X_text_onehot_m, y_text_onehot_m, test_size=0.1, random_state=0)
text2text_l4 = build_text2text_model_multiplication_layers_best()

history_l4=text2text_l4.fit(X_train,y_train,epochs=30,batch_size=10,validation_split=0.1,callbacks=[early_stopping])
results_l4 = text2text_l4.evaluate(X_test, y_test)
print("test loss, test acc:", results_l4)

pd.DataFrame(history_l4.history).plot(
figsize=(8, 5), grid=True, xlabel="Epoch",
style=["r--", "r--.", "b-", "b-*"],title='Multiplication: best text-to-text model')
plt.show()

"""#### Image-to-text RNN Model for multiplication"""

#simple one
def build_img2text_model_multiplication():

    img2text = tf.keras.Sequential()

    img2text.add(LSTM(256, input_shape=(max_query_length, 784)))

    img2text.add(RepeatVector(max_answer_length))

    img2text.add(LSTM(256, return_sequences=True))

    img2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))

    img2text.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    img2text.summary()

    return img2text

"""#### 75% train 25% test"""

(X_train, X_test, X_train_text, X_test_text, y_train, y_test) = train_test_split(
     X_img, X_text_onehot_m, y_text_onehot_m,
     test_size=0.25, random_state=0
)

X_train_flatten = X_train.reshape(X_train.shape[0], X_train.shape[1],-1)
print(X_train_flatten.shape)
X_test_flatten = X_test.reshape(X_test.shape[0], X_test.shape[1], -1)
print(X_test_flatten.shape)

# Define early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

img2text_1 = build_img2text_model_multiplication()
history_1=img2text_1.fit(X_train_flatten, y_train, epochs=20, batch_size=10, validation_split=0.1, callbacks=[early_stopping])
results_1 = img2text_1.evaluate(X_test_flatten, y_test)
print("test loss, test acc:", results_1)

"""#### 90% train 10% test"""

(X_train, X_test, X_train_text, X_test_text, y_train, y_test) = train_test_split(
     X_img, X_text_onehot_m, y_text_onehot_m,
     test_size=0.1, random_state=0
)

X_train_flatten = X_train.reshape(X_train.shape[0], X_train.shape[1],-1)
print(X_train_flatten.shape)
X_test_flatten = X_test.reshape(X_test.shape[0], X_test.shape[1], -1)
print(X_test_flatten.shape)

# Define early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

img2text_2 = build_img2text_model_multiplication()
history_2=img2text_2.fit(X_train_flatten, y_train, epochs=20, batch_size=10, validation_split=0.1, callbacks=[early_stopping])
results_2 = img2text_2.evaluate(X_test_flatten, y_test)
print("test loss, test acc:", results_2)

"""#### Add additional layers image to text"""

#one extra layer
def build_img2text_model_multiplication_layers():
    drop_out_rate = 0.25

    img2text = tf.keras.Sequential()
    img2text.add(LSTM(256, input_shape=(max_query_length, 784), return_sequences=True))

    img2text.add(LayerNormalization())
    img2text.add(LSTM(256,))
    img2text.add(LayerNormalization())
    img2text.add(Dropout(drop_out_rate))

    img2text.add(RepeatVector(max_answer_length))

    img2text.add(LSTM(512, return_sequences=True))

    img2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))


    img2text.compile(loss='categorical_crossentropy', optimizer= 'adam', metrics=['accuracy'])
    img2text.summary()

    return img2text

(X_train, X_test, X_train_text, X_test_text, y_train, y_test) = train_test_split(
     X_img, X_text_onehot_m, y_text_onehot_m,
     test_size=0.25, random_state=0
)

X_train_flatten = X_train.reshape(X_train.shape[0], X_train.shape[1],-1)
print(X_train_flatten.shape)
X_test_flatten = X_test.reshape(X_test.shape[0], X_test.shape[1], -1)
print(X_test_flatten.shape)

# Define early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

img2text_il1 = build_img2text_model_multiplication_layers()
history_il1=img2text_il1.fit(X_train_flatten, y_train, epochs=20, batch_size=10, validation_split=0.1, callbacks=[early_stopping])
results_il1 = img2text_il1.evaluate(X_test_flatten, y_test)
print("test loss, test acc:", results_il1)

#one extra layer with 512 units per layer
def build_img2text_model_multiplication_layers2():
    drop_out_rate = 0.25

    img2text = tf.keras.Sequential()
    img2text.add(LSTM(512, input_shape=(max_query_length, 784), return_sequences=True))

    img2text.add(LayerNormalization())
    img2text.add(LSTM(512,))
    img2text.add(LayerNormalization())
    img2text.add(Dropout(drop_out_rate))

    img2text.add(RepeatVector(max_answer_length))

    img2text.add(LSTM(512, return_sequences=True))

    img2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))


    img2text.compile(loss='categorical_crossentropy', optimizer= 'adam', metrics=['accuracy'])
    img2text.summary()

    return img2text

(X_train, X_test, X_train_text, X_test_text, y_train, y_test) = train_test_split(
     X_img, X_text_onehot_m, y_text_onehot_m,
     test_size=0.25, random_state=0
)

X_train_flatten = X_train.reshape(X_train.shape[0], X_train.shape[1],-1)
print(X_train_flatten.shape)
X_test_flatten = X_test.reshape(X_test.shape[0], X_test.shape[1], -1)
print(X_test_flatten.shape)

# Define early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

img2text_il2 = build_img2text_model_multiplication_layers2()
history_il2=img2text_il2.fit(X_train_flatten, y_train, epochs=20, batch_size=10, validation_split=0.1, callbacks=[early_stopping])
results_il2 = img2text_il2.evaluate(X_test_flatten, y_test)
print("test loss, test acc:", results_il2)

#two extra layers
def build_img2text_model_multiplication_layers3():
    drop_out_rate = 0.25

    img2text = tf.keras.Sequential()
    img2text.add(LSTM(256, input_shape=(max_query_length, 784), return_sequences=True))

    img2text.add(LayerNormalization())
    img2text.add(LSTM(256,return_sequences=True))
    img2text.add(LayerNormalization())
    img2text.add(Dropout(drop_out_rate))
    img2text.add(LSTM(256,))
    img2text.add(LayerNormalization())
    img2text.add(Dropout(drop_out_rate))

    img2text.add(RepeatVector(max_answer_length))

    img2text.add(LSTM(256, return_sequences=True))

    img2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))


    img2text.compile(loss='categorical_crossentropy', optimizer= 'adam', metrics=['accuracy'])
    img2text.summary()

    return img2text

(X_train, X_test, X_train_text, X_test_text, y_train, y_test) = train_test_split(
     X_img, X_text_onehot_m, y_text_onehot_m,
     test_size=0.25, random_state=0
)

X_train_flatten = X_train.reshape(X_train.shape[0], X_train.shape[1],-1)
print(X_train_flatten.shape)
X_test_flatten = X_test.reshape(X_test.shape[0], X_test.shape[1], -1)
print(X_test_flatten.shape)

# Define early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

img2text_il3 = build_img2text_model_multiplication_layers3()
history_il3=img2text_il3.fit(X_train_flatten, y_train, epochs=20, batch_size=10, validation_split=0.1, callbacks=[early_stopping])
results_il3 = img2text_il3.evaluate(X_test_flatten, y_test)
print("test loss, test acc:", results_il3)

#two extra layers
def build_img2text_model_multiplication_layers_4():
    drop_out_rate = 0.25

    img2text = tf.keras.Sequential()
    img2text.add(LSTM(256, input_shape=(max_query_length, 784), return_sequences=True))

    img2text.add(LayerNormalization())
    img2text.add(LSTM(256,return_sequences=True))
    img2text.add(LayerNormalization())
    img2text.add(Dropout(drop_out_rate))
    img2text.add(LSTM(256,return_sequences=True))
    img2text.add(LayerNormalization())
    img2text.add(Dropout(drop_out_rate))
    img2text.add(LSTM(256,))
    img2text.add(LayerNormalization())
    img2text.add(Dropout(drop_out_rate))

    img2text.add(RepeatVector(max_answer_length))

    img2text.add(LSTM(256, return_sequences=True))

    img2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))


    img2text.compile(loss='categorical_crossentropy', optimizer= 'adam', metrics=['accuracy'])
    img2text.summary()

    return img2text

(X_train, X_test, X_train_text, X_test_text, y_train, y_test) = train_test_split(
     X_img, X_text_onehot_m, y_text_onehot_m,
     test_size=0.25, random_state=0
)

X_train_flatten = X_train.reshape(X_train.shape[0], X_train.shape[1],-1)
print(X_train_flatten.shape)
X_test_flatten = X_test.reshape(X_test.shape[0], X_test.shape[1], -1)
print(X_test_flatten.shape)

# Define early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

img2text_il4 = build_img2text_model_multiplication_layers_4()
history_il4=img2text_il4.fit(X_train_flatten, y_train, epochs=10, batch_size=10, validation_split=0.1, callbacks=[early_stopping])
results_il4 = img2text_il4.evaluate(X_test_flatten, y_test)
print("test loss, test acc:", results_il4)

#two extra layers
def build_img2text_model_multiplication_layers_5():
    drop_out_rate = 0.25

    img2text = tf.keras.Sequential()
    img2text.add(LSTM(256, input_shape=(max_query_length, 784), return_sequences=True))

    img2text.add(LayerNormalization())
    img2text.add(LSTM(256,return_sequences=True))
    img2text.add(LayerNormalization())
    img2text.add(Dropout(drop_out_rate))
    img2text.add(LSTM(256,))
    img2text.add(LayerNormalization())
    img2text.add(Dropout(drop_out_rate))

    img2text.add(RepeatVector(max_answer_length))

    img2text.add(LSTM(512, return_sequences=True))

    img2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))


    img2text.compile(loss='categorical_crossentropy', optimizer= 'adam', metrics=['accuracy'])
    img2text.summary()

    return img2text

(X_train, X_test, X_train_text, X_test_text, y_train, y_test) = train_test_split(
     X_img, X_text_onehot_m, y_text_onehot_m,
     test_size=0.25, random_state=0
)

X_train_flatten = X_train.reshape(X_train.shape[0], X_train.shape[1],-1)
print(X_train_flatten.shape)
X_test_flatten = X_test.reshape(X_test.shape[0], X_test.shape[1], -1)
print(X_test_flatten.shape)

# Define early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

img2text_il5 = build_img2text_model_multiplication_layers_5()
history_il5=img2text_il5.fit(X_train_flatten, y_train, epochs=50, batch_size=10, validation_split=0.1, callbacks=[early_stopping])
results_il5 = img2text_il5.evaluate(X_test_flatten, y_test)
print("test loss, test acc:", results_il5)

#two extra layers
def build_img2text_model_multiplication_layers_best():
    drop_out_rate = 0.25

    img2text = tf.keras.Sequential()
    img2text.add(LSTM(128, input_shape=(max_query_length, 784), return_sequences=True))

    img2text.add(LayerNormalization())
    img2text.add(LSTM(128,return_sequences=True))
    img2text.add(LayerNormalization())
    img2text.add(Dropout(drop_out_rate))
    img2text.add(LSTM(256))
    img2text.add(LayerNormalization())
    img2text.add(Dropout(drop_out_rate))

    img2text.add(RepeatVector(max_answer_length))

    img2text.add(LSTM(256, return_sequences=True))

    img2text.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))


    img2text.compile(loss='categorical_crossentropy', optimizer= 'adam', metrics=['accuracy'])
    img2text.summary()

    return img2text

# img2text_m = tf.keras.Sequential()
# img2text_m.add(LSTM(512, input_shape=(max_query_length, 784), return_sequences=True))
# img2text_m.add(Dropout(drop_out_rate))
# img2text_m.add(Bidirectional(LSTM(256,)))  # Bidirectional LSTM
# img2text_m.add(RepeatVector(max_answer_length))
# img2text_m.add(LSTM(256, return_sequences=True))
# img2text_m.add(Dropout(drop_out_rate))
# img2text_m.add(BatchNormalization())
# img2text_m.add(TimeDistributed(tf.keras.layers.Dense(256, activation='relu')))
# img2text_m.add(TimeDistributed(Dense(len(unique_characters), activation='softmax')))

(X_train, X_test, X_train_text, X_test_text, y_train, y_test) = train_test_split(
     X_img, X_text_onehot_m, y_text_onehot_m,
     test_size=0.25, random_state=0
)

X_train_flatten = X_train.reshape(X_train.shape[0], X_train.shape[1],-1)
print(X_train_flatten.shape)
X_test_flatten = X_test.reshape(X_test.shape[0], X_test.shape[1], -1)
print(X_test_flatten.shape)

# Define early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

img2text_il6 = build_img2text_model_multiplication_layers_best()
history_il6=img2text_il6.fit(X_train_flatten, y_train, epochs=50, batch_size=10, validation_split=0.1, callbacks=[early_stopping])
results_il6 = img2text_il6.evaluate(X_test_flatten, y_test)
print("test loss, test acc:", results_il6)

pd.DataFrame(history_il6.history).plot(
figsize=(8, 5),  grid=True, xlabel="Epoch",
style=["r--", "r--.", "b-", "b-*"],title='Multiplication: Best model for image-to-text')
plt.show()

#stack the five images to create input images
stacked_image=[]
for i in range(X_img.shape[0]):
    stacked_image.append(np.concatenate([X_img[i][0], X_img[i][1], X_img[i][2], X_img[i][3], X_img[i][4]], axis=1))
s_image=np.array(stacked_image)

plt.imshow(s_image[0], cmap='gray')
plt.show()

#with cnn
import tensorflow as tf
from tensorflow.keras.layers import (
    Conv2D, BatchNormalization, MaxPooling2D, Dropout, Reshape, LSTM, Bidirectional, Flatten, RepeatVector, TimeDistributed, Dense
)
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import LearningRateScheduler, EarlyStopping
from sklearn.model_selection import train_test_split

drop_out_rate=0.25


# Normalize pixel values to [0, 1]
X_images = s_image / 255.0

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_images, y_text_onehot_m, test_size=0.2, random_state=42)

# Learning rate scheduler
def lr_schedule(epoch):
    lr = 1e-3
    if epoch > 5:
        lr *= 1e-1
    elif epoch > 10:
        lr *= 1e-2
    return lr

optimizer = Adam(learning_rate=lr_schedule(0))

# Early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

model_mu1 = tf.keras.models.Sequential([
    Conv2D(64, (3, 3), activation='relu', input_shape=(28, 140, 1)),
    BatchNormalization(),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    Dropout(drop_out_rate),
    BatchNormalization(momentum=0.9),
    MaxPooling2D((2, 2)),
    Conv2D(256, (3, 3), activation='relu'),
    Dropout(drop_out_rate),
    BatchNormalization(),
    MaxPooling2D((2, 2)),
    Reshape((5, -1)),
    LSTM(128, return_sequences=True),
    LSTM(128, return_sequences=True),
    # Bidirectional(LSTM(256, return_sequences=True)),
    Dropout(drop_out_rate),
    LayerNormalization(),
    Flatten(),
    RepeatVector(max_answer_length),
    LSTM(256, return_sequences=True),
    Dropout(drop_out_rate),
    # TimeDistributed(Dense(64, activation='relu')),
    TimeDistributed(Dense(len(unique_characters), activation='softmax'))
])

# Compile the model
model_mu1.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

# Reshape the data to include the channel dimension
X_train_reshaped = X_train.reshape((X_train.shape[0], 28, 140, 1))
X_test_reshaped = X_test.reshape((X_test.shape[0], 28, 140, 1))

# Train the model
history_mu1 = model_mu1.fit(X_train_reshaped, y_train, epochs=50, batch_size=32, validation_data=(X_test_reshaped, y_test), callbacks=[early_stopping, LearningRateScheduler(lr_schedule)])

# Evaluate the model
loss, accuracy = model_mu1.evaluate(X_test_reshaped, y_test)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

"""##### A different approach: Predict text on image and then calculate the arithmetic operation using cnns and rnns together"""

#stack the five images to create input images
stacked_image=[]
for i in range(X_img.shape[0]):
    stacked_image.append(np.concatenate([X_img[i][0], X_img[i][1], X_img[i][2], X_img[i][3], X_img[i][4]], axis=1))
s_image=np.array(stacked_image)

plt.imshow(s_image[0], cmap='gray')
plt.show()

#first attempt
X_text_labels_encoded = encode_labels(X_text)

# Preprocess the images
X_images = s_image / 255.0  # Normalize pixel values to [0, 1]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_images, X_text_labels_encoded, test_size=0.2, random_state=42)

model_im = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 140, 1)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Reshape((5, -1)),  # Flatten before LSTM, assuming 5 time steps
    tf.keras.layers.LSTM(128, return_sequences=True),
    tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(64, activation='relu')),
    tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(len(unique_characters), activation='softmax'))
])


# Compile the model
model_im.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Reshape the data to include the channel dimension
X_train_reshaped = X_train.reshape((X_train.shape[0], 28, 140, 1))
X_test_reshaped = X_test.reshape((X_test.shape[0], 28, 140, 1))

# Train the model_im
history_im=model_im.fit(X_train_reshaped, y_train, epochs=10, batch_size=32, validation_split=0.1)

# Evaluate the model
loss, accuracy = model_im.evaluate(X_test_reshaped, y_test)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

def calculate_results(expressions):
    results = []
    for expression in expressions:
        try:
            result = eval(expression)
            results.append(result)
        except Exception as e:
            results.append(f"Error: {str(e)}")
    return results


predictions = model_im.predict(X_test_reshaped)
# Decode the one-hot encoded predictions and real labels
decoded_predictions = [decode_labels(pred) for pred in predictions]
decoded_real_labels = [decode_labels(ys) for ys in y_test]


results_pred = calculate_results(decoded_predictions)
results_real = calculate_results(decoded_real_labels)

count=0
for expression_pred,expression_real, result_pred,result_real in zip(decoded_predictions,decoded_real_labels, results_pred,results_real):
    if result_pred==result_real:
      count=count+1
print(f'correct multiplication result: {count/len(results_real) * 100:.2f}%')

total_chars = 0
correct_chars = 0

# Calculate character-level accuracy
for true_chars, pred_chars in zip(decoded_real_labels, decoded_predictions):
    total_chars += max(len(true_chars), len(pred_chars))
    correct_chars += sum(t == p for t, p in zip(true_chars, pred_chars))

char_accuracy = correct_chars / total_chars

print(f'Character-level Accuracy: {char_accuracy * 100:.2f}%') #same as model accuracy


# Convert sequences of characters back to strings
y_pred_seqs = [''.join(seq) for seq in decoded_predictions]
y_test_seqs = [''.join(seq) for seq in decoded_real_labels]

# Calculate sequence-level accuracy
correct_seqs = sum(true_seq == pred_seq for true_seq, pred_seq in zip(y_test_seqs, y_pred_seqs))
sequence_accuracy = correct_seqs / len(y_test_seqs)

print(f'Sequence-level Accuracy: {sequence_accuracy * 100:.2f}%') #all the expression orrect->correct result of multiplication

#best model

drop_out_rate=0.25

X_text_labels_encoded = encode_labels(X_text)

# Preprocess the images
X_images = s_image / 255.0  # Normalize pixel values to [0, 1]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_images, X_text_labels_encoded, test_size=0.2, random_state=42)

model_im2 = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu', input_shape=(28, 140, 1)),
    BatchNormalization(),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
    Dropout(drop_out_rate),
    BatchNormalization(),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(512, (3, 3), activation='relu'),
    Dropout(drop_out_rate),
    BatchNormalization(),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Reshape((5, -1)),  # Flatten before LSTM, assuming 5 time steps
    tf.keras.layers.LSTM(128, return_sequences=True),
    tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(64, activation='relu')),
    tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(len(unique_characters), activation='softmax'))
])


# Compile the model
model_im2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Reshape the data to include the channel dimension
X_train_reshaped = X_train.reshape((X_train.shape[0], 28, 140, 1))
X_test_reshaped = X_test.reshape((X_test.shape[0], 28, 140, 1))

# Train the model
history_im2=model_im2.fit(X_train_reshaped, y_train, epochs=10, batch_size=32, validation_split=0.1)

# Evaluate the model
loss, accuracy = model_im2.evaluate(X_test_reshaped, y_test)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

predictions_im2 = model_im2.predict(X_test_reshaped)
# Decode the one-hot encoded predictions and real labels
decoded_predictions = [decode_labels(pred) for pred in predictions_im2]
decoded_real_labels = [decode_labels(ys) for ys in y_test]


results_pred = calculate_results(decoded_predictions)
results_real = calculate_results(decoded_real_labels)

count=0
for expression_pred,expression_real, result_pred,result_real in zip(decoded_predictions,decoded_real_labels, results_pred,results_real):
    if result_pred==result_real:
      count=count+1
print(f'correct multiplication result: {count/len(results_real) * 100:.2f}%')

total_chars = 0
correct_chars = 0

# Calculate character-level accuracy
for true_chars, pred_chars in zip(decoded_real_labels, decoded_predictions):
    total_chars += max(len(true_chars), len(pred_chars))
    correct_chars += sum(t == p for t, p in zip(true_chars, pred_chars))

char_accuracy = correct_chars / total_chars

print(f'Character-level Accuracy: {char_accuracy * 100:.2f}%') #same as model accuracy


# Convert sequences of characters back to strings
y_pred_seqs = [''.join(seq) for seq in decoded_predictions]
y_test_seqs = [''.join(seq) for seq in decoded_real_labels]

# Calculate sequence-level accuracy
correct_seqs = sum(true_seq == pred_seq for true_seq, pred_seq in zip(y_test_seqs, y_pred_seqs))
sequence_accuracy = correct_seqs / len(y_test_seqs)

print(f'Sequence-level Accuracy: {sequence_accuracy * 100:.2f}%') #all the expression orrect->correct result of multiplication